# étape de build
FROM node:lts-alpine
WORKDIR /var/www/html/vue
# COPY ./src/vue/package*.json ./src/vue:/var/www/html/vue
# RUN npm install
# COPY ./src/vue .
# RUN npm run build

# étape de production
# FROM nginx:stable-alpine as production-stage
# COPY --from=build-stage /app/dist /usr/share/nginx/html
# COPY --from=build-stage /app/nginx.conf /etc/nginx/conf.d/default.conf
# EXPOSE 80
# CMD ["nginx", "-g", "daemon off;"]
CMD [ "npm","run","serve" ]