version: '3'

networks:
    laravel:
        driver: bridge
services:
    nginx:
        image: nginx:stable-alpine
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./src/api:/var/www/html/api
            - ./src/vue:/var/www/html/vue
            # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
            - mysql
            - vue
        networks:
            - laravel
    mysql:
        image: mysql:8.0.28
        container_name: mysql
        # restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_USER: username
            MYSQL_PASSWORD: password
            MYSQL_DATABASE: civic_prob_map
            SERVICE_TAG: dev
            SERVICE_NAME: mysql
        # volumes:
        #     - ./mysql:/var/lib/mysql
        networks:
            - laravel
    php:
        build:
            context: .
            dockerfile: Dockerfile_php
        container_name: php
        volumes:
            - ./src/api:/var/www/html/api
        ports:
            - 9000:9000
        networks:
            - laravel
    vue:
        build: 
            context: .
            dockerfile: Dockerfile_vue
        container_name : "vue"
        volumes:
            - ./src/vue:/var/www/html/vue
        ports:
            - 1337:1337
        depends_on:
            - "php"
            - "mysql"
        networks:
            - laravel
